### ISSUE TITLE
Run Preview Augmentations on Separate Thread 

### ISSUE THREAD

**Issue by vjsrinivas** [Rus00/Noisey-image#11]
Some augmentations (such as salt & pepper) currently take a non-trivial amount of time to process. Since it is a blocking function on the same thread as GUI, using a separate thread to run the preview augmentations would allow a snappier GUI.

**Comment by vjsrinivas** [comment]
@Rus00 Was this completed?

**Comment by Rus00** [comment]
> @Rus00 Was this completed?

After optimizing the salt&pepper algorithm, I don't think we need to run the augmentations on a separate thread. I commented out the code for this. I feel like it just made the code harder to read.

**Comment by vjsrinivas** [comment]
Closing until we notice any noticeable performance issues because of the previews.
