### ISSUE TITLE
Run the models on augmented image instead of original image

### ISSUE THREAD

**Issue by Rus00** [Rus00/Noisey-image#16]
Currently, the app doesn't save the augmented image. It just displays it on the qlabel. My plan is to add the augmented images to the list items.

**Comment by vjsrinivas** [comment]
Pushing the UI controls related to this that I've added

**Comment by vjsrinivas** [comment]
This issue has been addressed in 6475957da52084faef410e2401ee2dba6239e092
Needs to be tested more in case of additional bugs. Reopen if that is the case.
