### ISSUE TITLE
Weights download feature failed

### ISSUE THREAD

**Issue by Rus00** [Rus00/Noisey-image#19]
![image](https://user-images.githubusercontent.com/49564286/144771764-b79dbe21-356f-4e80-8b85-04450108562d.png)

**Comment by Rus00** [comment]
It fails because it tries to open the folders src/obj_detector/weights and /src/ckpt/ade20k-hrnetv2-c1. These folders do not exist when you first clone the repository.

**Comment by vjsrinivas** [comment]
Ah good catch. We should just add a `os.mkdirs` in the autodownload function to resolve this.

**Comment by vjsrinivas** [comment]
Incorporated fix in 9e61156d40af4ec8bcd86c959c942600b2bc69e1
