### ISSUE TITLE
GUI for download wights feature

### ISSUE THREAD

**Issue by Rus00** [Rus00/Noisey-image#20]
It takes a very long time to download the weights. We should have a GUI element or a new window that tells the user that the weights are downloading.

**Comment by vjsrinivas** [comment]
For GUI, we will run a function (might already exist in some form) to check if weights are there or not.
If not there, we will display a dialog box with one action - "Download the Weights". Then we will switch to a window that shows download progress.

**Comment by vjsrinivas** [comment]
GUI created in newest commit:  9e61156d40af4ec8bcd86c959c942600b2bc69e1
Closing issue for now. Might reopen to discuss failsafe for downloading error.
