### ISSUE TITLE
Default "Segmentation" Image When First Launch

### ISSUE THREAD

**Issue by vjsrinivas** [Rus00/Noisey-image#25]
Basically re-implementing an old feature where the segmentation result of the default car image is shown.

**Comment by Rus00** [comment]
> Basically re-implementing an old feature where the segmentation result of the default car image is shown.

Is it better for the segmentation result to be saved somewhere so it can just be imported when the app is launched or should the segmentation model be run when the app is launched?

**Comment by vjsrinivas** [comment]
I believe the result only would be fine. Maybe we need to look into changing the default parameters that are loaded at the beginning. They were chosen randomly.

**Comment by vjsrinivas** [comment]
Replaced with default face image
